spring.application.name=ExpenseIQ
server.port=${PORT:8080}
server.forward-headers-strategy=native

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/expenseiq
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:8000,http://127.0.0.1:8000,http://localhost:5500,http://127.0.0.1:5500,http://localhost:3000,http://127.0.0.1:3000

# OTP
app.otp.expiration=300000
app.otp.length=6

# Email Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sanketpatils984@gmail.com
spring.mail.password=kpph fgan lwft omlz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
